    scala_binary(
      name = "scalafix_cp_buildergithub_ianoc__ianoc",
      main_class = "none",
      deps = [
        "////src/scala/com/github/ianoc:ianoc",
        "//3rdparty/jvm/org/scala_lang:scala_compiler",
        
      ],
      runtime_deps = [
        "//3rdparty/jvm/org/scala_lang:scala_compiler",
        "//3rdparty/jvm/jline",
      ],
      visibility = ["//visibility:public"]
    )

