name: Release
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz
            artifact: scalafmt-macos
          - os: ubuntu-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
            artifact: scalafmt-linux
    steps:
      - uses: actions/checkout@v2
      - run: cp bazel scalafmt
        env:
          CI: true
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: scalafmt
  make_release:
    name: Display results
    needs: native-image
    runs-on: ubuntu-latest
    steps:
      - name: Download linux scalafmt
        uses: actions/download-artifact@v1
        with:
          name: scalafmt-linux
      - name: Download linux scalafmt
        uses: actions/download-artifact@v1
        with:
          name: scalafmt-macos
      - uses: "marvinpinto/action-automatic-releases@v0.3.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1-${{ github.run_number }}"
          prerelease: false
          title: "Auto generated release"
          files: |
            scalafmt-macos
            scalafmt-linux
        id: "automatic_releases"
