name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Bazel output cache
      id: cache-primes
      uses: actions/cache@v1
      with:
        path: "${{ github.workspace }}/.bazel-cache"
        key: ${{ runner.os }}-bazel-out-${{ github.run_id}}
        restore-keys: |
          ${{ runner.os }}-bazel-out-
    - name: Configure bazel config for actions
      run: |
        echo "build --config github_actions" > user.bazelrc
        echo "build --disk_cache ${{ github.workspace }}/.bazel-cache/disk-cache" >> user.bazelrc
        echo "build --repository_cache ${{ github.workspace }}/.bazel-cache/repo-cache" >> user.bazelrc
    - name: Ensure bazel on box
      run: ./bazel
      env:
        BAZEL_BIN_LOC: "${{ github.workspace }}/.bazel-cache/bazel-bin"
    - name: Run bazel build all
      run: ./bazel build //...
      env:
        BAZEL_BIN_LOC: "${{ github.workspace }}/.bazel-cache/bazel-bin"
    # - name: Run bazel test all
    #   run: |
    #     ./bazel test //...

