name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Bazel output cache
      id: cache-primes
      uses: actions/cache@v1
      with:
        path: ~/.bazel-cache
        key: ${{ runner.os }}-bazel-out-${{ github.run_id}}
        restore-keys: |
          ${{ runner.os }}-bazel-out-
    - name: Configure bazel config for actions
      run: echo "build --config github_actions" > user.bazelrc
    - name: Ensure bazel on box
      run: ./bazel
      env:
        BAZEL_BIN_LOC: $HOME/.bazel-cache/bazel-bin
    - name: Run bazel build all
      run: ./bazel build //...
      env:
        BAZEL_BIN_LOC: $HOME/.bazel-cache/bazel-bin
    # - name: Run bazel test all
    #   run: |
    #     ./bazel test //...

